name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      android: ${{ steps.filter.outputs.android }}
      stm: ${{ steps.filter.outputs.stm }}
      root_files: ${{ steps.filter.outputs.root_files }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            android:
              - 'app/src/main/**'
              - 'gradle/**'
              - 'build.gradle'
              - 'gradle.properties'
              - 'gradlew'
              - 'gradlew.bat'
              - 'settings.gradle'
            stm:
              - 'app/src/main/cpp/**'
            root_files:
              - '.github/**'
              - 'make/**'
              - 'make.py'
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1 # Optional fallback tag to use when no tag can be found
          prefix: v
      - name: 'Get Next Version'
        id: get-next-version
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
          strict: false
      - name: Show next version
        run: echo ${{ steps.get-next-version.outputs.major }}
