name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      next_version: ${{ steps.next_version.outputs.next_version }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          prefix: v
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: 'Get Next Version'
        id: next_version
        run: |
          current_version=$(echo ${{ steps.previoustag.outputs.tag }} | tr -d 'v')
          echo current_version=$current_version
          next_version=$(echo $current_version | awk -F. -v OFS=. '{$NF++;print}')
          echo "next_version=$next_version" >> $GITHUB_OUTPUT
          echo next_version=$next_version
      - name: Show next version
        run: echo ${{ steps.next_version.outputs.next_version }}

  update_tag:
    runs-on: ubuntu-latest
    needs: changes
    steps:
      - uses: actions/checkout@v3
      - name: Update tag with the next version
        run: |
          next_version=${{ needs.changes.outputs.next_version }}
          git config --global user.email ""
          git config --global user.name "github-actions"
          git tag -a v$next_version -m "v$next_version"
          git push origin v$next_version
