name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      android: ${{ steps.filter.outputs.android }}
      stm: ${{ steps.filter.outputs.stm }}
      root_files: ${{ steps.filter.outputs.root_files }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          prefix: v
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: 'Get Next Version'
        id: next_version
        run: |
          current_version=$(echo ${{ steps.previoustag.outputs.tag }} | tr -d 'v')
          echo $current_version
          next_version=$(echo $current_version | awk -F. -v OFS=. '{$NF++;print}')
          echo "next_version=$next_version" >> $GITHUB_OUTPUT
          echo $next_version
      - name: Show next version
        run: echo ${{ steps.next_version.outputs.next_version }}
      - name: Update tag with the next version
        run: |
          git config --global user.email "
          git config --global user.name "github-actions"
          git tag -a v${{ steps.next_version.outputs.next_version }} -m "v${{ steps.next_version.outputs.next_version }}"
          git push origin v${{ steps.next_version.outputs.next_version }}
