name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      android: ${{ steps.filter.outputs.android }}
      stm: ${{ steps.filter.outputs.stm }}
      root_files: ${{ steps.filter.outputs.root_files }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          prefix: v
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: 'Get Next Version'
        run: echo ${{ steps.previoustag.outputs.tag }}
