name: CD

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get tag
        run: git describe --tags --abbrev=0 || echo "no tags"
  check_build:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      status: ${{ steps.check_tag.outputs.status }}
    steps:
      - uses: actions/checkout@v2
      - name: Check tag
        id: check_tag
        run: |
          echo "${{ github.event.ref }}"
          TAG=$(echo ${{ github.event.ref }} | cut -f3- -d'/')
          echo $TAG
          [[ $TAG =~ ^v([0-9]\d*)\.([0-9]\d*) ]] && echo "::set-output name=status::build"  || echo "::set-output name=status::skip-build"
  build:
    needs: check_build
    if: "needs.check_build.outputs.status == 'build'"
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.build.conclusion }}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        id: build
        run: echo build
  deploy:
    needs:
      - check_build
      - build
    #if: "needs.check_build.outputs.status == 'skip-build' || !contains(needs.build.outputs.status, 'failure')"
    if: "needs.check_build.outputs.status == 'skip-build'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get tag
        run: get describe --tags --abbrev=0 || echo "no tags"
