name: CD

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get tag
        run: git describe --tags --abbrev=0 || echo "no tags"
  check_build:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      status: ${{ steps.check_tag.conclusion }}
    steps:
      - uses: actions/checkout@v2
      - name: Check tag
        id: check_tag
        run: |
          echo "${{ github.event.ref }}"
          TAG=$(echo ${{ github.event.ref }} | cut -f3- -d'/')
          echo $TAG
          [[ $A =~ ^v([0-9]\d*)\.([0-9]\d*) ]] && exit 0 || exit 1
  build:
    needs: check-build
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.build.conclusion }}
    steps:
      - name: Check build
        if: "!contains(needs.check_build.outputs.status, 'failure')"
        run: exit 1
      - uses: actions/checkout@v2
      - name: Build
        id: build
        run: echo build
  deploy:
    if: "!contains(needs.build.outputs.status, 'failure')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get tag
        run: get describe --tags --abbrev=0 || echo "no tags"
