name: CD

on:
  push:
    branches:
      - master
    tags:
      - v1.*


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get tag
        run: git describe --tags --abbrev=0 || echo "no tags"
  check-build:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      status: ${{ steps.check_tag.outputs.status }}
    steps:
      - uses: actions/checkout@v2
      - name: Check tag
        id: check_tag
        run: |
          echo "${{ github.event.ref }}"
          TAG=$(echo ${{ github.event.ref }} | cut -f3- -d'/')
          echo $TAG
          [[ $TAG =~ ^v([0-9]\d*)\.([0-9]\d*) ]] && echo "::set-output name=status::build"  || echo "::set-output name=status::skip-build"
  build-images:
    needs: check-build
    if: "needs.check-build.outputs.status == 'build'"
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.build.conclusion }}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        id: build
        run: |
          echo build
          exit 0

  skipped-build-images:
    needs: check-build
    if: "needs.check-build.outputs.status == 'skip-build'"
    runs-on: ubuntu-latest

  deploy:
    needs: build-images
    if: "always() && (needs.build-images.result == 'skipped' || needs.build-images.result == 'success')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get tag
        run: get describe --tags --abbrev=0 || echo "no tags"
