name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Cache docker layers'
        uses: actions/cache@v2
        with:
          path: $RUNNER_TEMP/abc
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - run: |
          ls -R $RUNNER_TEMP
          mkdir -p $RUNNER_TEMP/abc
      - run: echo ${{ github.sha }} > $RUNNER_TEMP/abc/f1
