name: C2

on:
  push:
    branches:
      - master
    tags:
      - v1.*prod
  workflow_dispatch:
    inputs:
      stage:
        required: false
        default: "test"
        description: "Initial job"

jobs:
  test:
    if: "!(startsWith(github.event.ref, 'refs/tags/v') && contains(github.event.ref, 'prod'))"
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"

  build-images:
    needs: test
    if: ${{ github.event.inputs.stage  == github.job }}
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo build
          exit 0

  skipped-build-images:
    needs: build-images
    if: always() && (needs.build-images.result == 'failure')
    runs-on: ubuntu-latest
    steps:
      - name: 'Skip image'
        run: echo ${{needs.build-images.result}} && exit 0

  deploy:
    if: ${{ github.event.inputs.stage  == github.job }}
    needs: 
      - build-images
        #- skipped-build-images
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy"

  deploy-prod:
    needs: deploy
    if: startsWith(github.event.ref, 'refs/tags/v') && contains(github.event.ref, 'prod')
    runs-on: ubuntu-latest
    steps:
      - name: 'Deploy to prod'
        run: echo ${{github.event.ref}}

  post-deploy-prod:
    needs: deploy-prod
    runs-on: ubuntu-latest
    steps:
      - name: 'Clean up'
        run: echo 'sss'


  post-deploy:
    if: ${{ github.event.inputs.stage  == github.job }}
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "post-deploy"
